name: Deploy To S3

on:
  push:
    branches: [CRA]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout v2
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Setup .env for CRA
        run: |
          echo "REACT_APP_SERVER_URL=${{ secrets.REACT_APP_SERVER_URL }}" >> .env
          echo "REACT_APP_SOCKET_SERVER_URL=${{ secrets.REACT_APP_SOCKET_SERVER_URL }}" >> .env
          cp .env build/.env

      - name: Deploy To S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
          SOURCE_DIR: "build"
